name: Bug Report
description: Create a report to help us fix a bug 
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Please make sure the bug isn't reported already to avoid double work.
        
        ***Please submit the bug report in English only!*** 🇬🇧
  - type: input
    id: build-number
    attributes:
      label: Build number
      description: Please provide the build number of your installation as shown at the top right of the screen.
      placeholder: e.g. 215
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: Please tell us as detailed as possible what you did and what went wrong.
      placeholder: What happened? What did you expect?
    validations:
      required: true
  - type: textarea
    id: bug-reproduce
    attributes:
      label: Steps to reproduce the bug
      placeholder: Please let us know what we have to do to reproduce this bug
  - type: textarea
    id: bug-savegame
    attributes:
      label: Savegame file
      description: Savegames are located in `%USERPROFILE%\AppData\LocalLow\Hovgaard Games\Big Ambitions` in a separate folder for every alpha version
      placeholder: Please attach your savegame file here. You have to change the file extension from .json to .txt in order to attach it.
  - type: textarea
    id: bug-screenshots
    attributes:
      label: Screenshots or videos
      placeholder: Please attach any screenshots or videos of the issue if available
