name: New Bug Report
description: Create a report to help us fix a bug 
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: build-number
    attributes:
      label: Build number
      description: Please provide the build number of your installation as shown at the top right of the screen.
      placeholder: e.g. 215
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: |
        Please tell us as detailed as possible what you did and what went wrong. If possible, please also provide screenshots/videos and a savegame.
        When adding a savegame file, you have to change the file extension from .json to .txt
      value: |
        Description:
        
        Steps to reproduce the bug:
        
        Savegame, if available (drag&drop or copy&paste it here):
        
        Screenshots (drag&drop or copy&paste it here):
      placeholder: What happened? What did you expect?
    validations:
      required: true
      
